version: "3.9"

services:
  apirelatorios.webapi:
    image: apirelatorioswebapi
    build:
      context: .
      dockerfile: APIRelatorios.WebAPI/Dockerfile
    depends_on:
      - postgres-db
      - api-docx
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080/
      ConnectionStringsHost: postgres-db
      ConnectionStringsPort: "5432"
      ConnectionStringsDatabase: RelatorioDB
      ConnectionStringsUser: AdminTeste
      ConnectionStrings__Password: Teste123
    expose:
      - "8080"

    dns:
      - 8.8.8.8
      - 1.1.1.1

    restart: unless-stopped

    networks:
      - backend

  api-docx:
    build:
      context: ./PythonDocx
      dockerfile: Dockerfile
    expose:
      - "8000"

    dns:
      - 8.8.8.8
      - 1.1.1.1

    restart: unless-stopped

    networks:
      - backend

  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_DB: RelatorioDB
      POSTGRES_USER: AdminTeste
      POSTGRES_PASSWORD: Teste123
    volumes:
      - pgdata:/var/lib/postgresql/data

    restart: unless-stopped

    networks:
      - backend

  nginx:
  image: nginx:1.25
  container_name: nginx_proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./letsencrypt:/etc/letsencrypt:ro
  depends_on:
    - apirelatorios.webapi

  restart: unless-stopped

  networks:
    - frontend
    - backend

volumes:
  pgdata:

networks:
  frontend:
  backend: