events {}

http {
    client_max_body_size 100M;
    server {
    listen 80;
    server_name gustavoalvescorrea.cloud www.gustavoalvescorrea.cloud;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
    listen 443 ssl;
    server_name gustavoalvescorrea.cloud www.gustavoalvescorrea.cloud;

    ssl_certificate /etc/letsencrypt/live/gustavoalvescorrea.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gustavoalvescorrea.cloud/privkey.pem;

        location / {
            proxy_pass http://apirelatorios.webapi:8080;
        }
    }
}