// <auto-generated />
using System;
using APIRelatorios.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIRelatorios.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.Imagem", b =>
                {
                    b.Property<int>("ImagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImagemId"));

                    b.Property<int>("Cep")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("RotaID")
                        .HasColumnType("integer");

                    b.Property<int?>("RotaId")
                        .HasColumnType("integer");

                    b.HasKey("ImagemId");

                    b.HasIndex("RotaID");

                    b.HasIndex("RotaId");

                    b.ToTable("Imagem");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.Rota", b =>
                {
                    b.Property<int>("RotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RotaId"));

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeRota")
                        .HasColumnType("text");

                    b.HasKey("RotaId");

                    b.ToTable("Rota");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Fiscais");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.UsuarioRota", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("RotaID")
                        .HasColumnType("integer");

                    b.HasKey("UserID", "RotaID");

                    b.HasIndex("RotaID");

                    b.ToTable("UsuarioRotas");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.Imagem", b =>
                {
                    b.HasOne("APIRelatorios.Dommain.Entities.Rota", "Rota")
                        .WithMany()
                        .HasForeignKey("RotaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIRelatorios.Dommain.Entities.Rota", null)
                        .WithMany("Images")
                        .HasForeignKey("RotaId");

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.UsuarioRota", b =>
                {
                    b.HasOne("APIRelatorios.Dommain.Entities.Rota", "Rota")
                        .WithMany("Fiscais")
                        .HasForeignKey("RotaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIRelatorios.Dommain.Entities.User", "User")
                        .WithMany("usuarioRotas")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.Rota", b =>
                {
                    b.Navigation("Fiscais");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.User", b =>
                {
                    b.Navigation("usuarioRotas");
                });
#pragma warning restore 612, 618
        }
    }
}
