// <auto-generated />
using System;
using APIRelatorios.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIRelatorios.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.CheckList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("EvidenciaRotaId")
                        .HasColumnType("uuid");

                    b.Property<int[]>("SubTemaAlimentadores")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("TemaCheck")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvidenciaRotaId")
                        .IsUnique();

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.EvidenciaRota", b =>
                {
                    b.Property<Guid>("EvidenciaRotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alimentador")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("Emergencial")
                        .HasColumnType("boolean");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FiscalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identificacão")
                        .HasColumnType("text");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid");

                    b.HasKey("EvidenciaRotaId");

                    b.HasIndex("RotaId");

                    b.ToTable("EvidenciaRota");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.ImageData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("EvidenciaRotaId")
                        .HasColumnType("uuid");

                    b.Property<string>("LowUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvidenciaRotaId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.Rota", b =>
                {
                    b.Property<Guid>("RotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alimentador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Concessionarias")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Km")
                        .HasColumnType("double precision");

                    b.Property<string>("NomeRota")
                        .HasColumnType("text");

                    b.Property<string>("TipoRota")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<bool>("isValid")
                        .HasColumnType("boolean");

                    b.HasKey("RotaId");

                    b.ToTable("Rota");

                    b.HasDiscriminator<string>("TipoRota").HasValue("Rota");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("UserId");

                    b.ToTable("Fiscais");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.UsuarioRota", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RotaId");

                    b.HasIndex("RotaId");

                    b.ToTable("UsuarioRotas");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.RotaRetorno", b =>
                {
                    b.HasBaseType("APIRelatorios.Dommain.Entities.Rota");

                    b.HasDiscriminator().HasValue("RotaRetorno");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.CheckList", b =>
                {
                    b.HasOne("APIRelatorios.Dommain.Entities.EvidenciaRota", "EvidenciaRota")
                        .WithOne("CheckList")
                        .HasForeignKey("APIRelatorios.Dommain.Entities.CheckList", "EvidenciaRotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvidenciaRota");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.EvidenciaRota", b =>
                {
                    b.HasOne("APIRelatorios.Dommain.Entities.Rota", "Rota")
                        .WithMany("Images")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.ImageData", b =>
                {
                    b.HasOne("APIRelatorios.Dommain.Entities.EvidenciaRota", "EvidenciaRota")
                        .WithMany("Images")
                        .HasForeignKey("EvidenciaRotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvidenciaRota");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.UsuarioRota", b =>
                {
                    b.HasOne("APIRelatorios.Dommain.Entities.Rota", "Rota")
                        .WithMany("Fiscais")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIRelatorios.Dommain.Entities.User", "User")
                        .WithMany("usuarioRotas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.EvidenciaRota", b =>
                {
                    b.Navigation("CheckList")
                        .IsRequired();

                    b.Navigation("Images");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.Rota", b =>
                {
                    b.Navigation("Fiscais");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("APIRelatorios.Dommain.Entities.User", b =>
                {
                    b.Navigation("usuarioRotas");
                });
#pragma warning restore 612, 618
        }
    }
}
